#!/usr/bin/env ansible-playbook
---
- name: Copy FERSAT docs to server
  hosts: fersat1
  become: True
  become_user: root
  become_method: sudo

  vars_files:
    - vars/fersat.yml

  roles:
    - { role: deploy-docs }
